version: '3.8'

services:
  mongodb:
    image: mongo:7.0
    container_name: todo-database
    restart: unless-stopped
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    environment:
      MONGO_INITDB_DATABASE: todo_db
    networks:
      - todo-network

  todo-app:
    build: .
    container_name: todo-aplikacja
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      - MONGODB_URI=mongodb://mongodb:27017/todo_db
      - NODE_ENV=production
    depends_on:
      - mongodb
    networks:
      - todo-network
    command: sh -c "sleep 10 && npm start"

volumes:
  mongodb_data:
    driver: local

networks:
  todo-network:
    driver: bridge